---
apiVersion: deckhouse.io/v1
kind: User
metadata:
  name: admin
spec:
  email: admin@cluster.local
  password: JDJ5JDEwJGxTSHpOU25EOXlYUUY1UlVTRTB2V09zektSU29hdGhjOC5XY1o0ckEvblZZL0lvRGdVSmIyCgo=
---
apiVersion: deckhouse.io/v1alpha1
kind: Group
metadata:
  name: admins
spec:
  name: admins
  members:
    - kind: User
      name: admin
---
apiVersion: deckhouse.io/v1
kind: NodeGroup
metadata:
  name: worker
spec:
  disruptions:
    approvalMode: Automatic
  kubelet:
    containerLogMaxFiles: 4
    containerLogMaxSize: 50Mi
    maxPods: 200
    resourceReservation:
      mode: "Off"
  nodeType: Static