---
apiVersion: v1
kind: Namespace
metadata:
  name: sds-e2e-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sds-e2e-test
  namespace: sds-e2e-test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: sds-e2e-test
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: sds-e2e-test
    spec:
      containers:
        - command:
            - sleep
            - infinity
          image: golang:1.22.4-bullseye
          imagePullPolicy: Always
          name: sds-e2e-test
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /app
              name: sds-e2e-test
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: registrysecret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: sds-e2e-test
      terminationGracePeriodSeconds: 30
      volumes:
        - name: sds-e2e-test
          persistentVolumeClaim:
            claimName: sds-e2e-test
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sds-e2e-test
  namespace: sds-e2e-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sds-e2e-test
  namespace: sds-e2e-test
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: d8:sds-e2e-test
rules:
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
    apiGroups:
      - storage.deckhouse.io
    resources:
      - blockdevices
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - virtualization.deckhouse.io
    resources:
      - ""
  - verbs:
      - "*"
    apiGroups:
      - "*"
    resources:
      - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: d8:sds-e2e-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: d8:sds-e2e-test
subjects:
  - kind: ServiceAccount
    name: sds-e2e-test
    namespace: sds-e2e-test
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: d8:sds-e2e-test
  namespace: sds-e2e-test
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - virtualization.deckhouse.io
    resources:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: d8:sds-e2e-test
  namespace: sds-e2e-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: d8:sds-e2e-test
subjects:
  - kind: ServiceAccount
    name: sds-e2e-test
    namespace: sds-e2e-test
